# https://docs.helix-editor.com/editor.html
theme = "onedark"
# theme = "tokyonight_storm" # No diff between > and **
# theme = "base16_transparent"
# theme = "base16"

[editor]
line-number = "relative"
mouse = true
cursorline = true
bufferline = "multiple"
rulers = [80, 100]
scrolloff = 2
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true

[keys.normal]
X = ["extend_line_above"]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[keys.normal.m]
c = "@miWms<A-`>"

[keys.insert]
# C-esc = ["normal_mode"]
# A-esc = ["normal_mode"]
j = { k = "normal_mode" }
