[[grammar]]
name = "c"
source = { git = "https://github.com/tree-sitter/tree-sitter-c", rev = "7175a6dd5fc1cee660dce6fe23f6043d75af424a" }

[language-server]
clangd = { command = "clangd" }

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "c"
auto-format = true
scope = "source.c"
injection-regex = "c"
file-types = ["c"] # TODO: ["h"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "clangd" ]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "clang-format"}

# https://github.com/Myriad-Dreamin/tinymist/blob/main/editors/neovim/Configuration.md
[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "onType", outputPath = "$root/build/$dir/$name" }

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { console = "internalConsole", program = "{0}" }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = [ "pid" ]
args = { console = "internalConsole", pid = "{0}" }

[[language.debugger.templates]]
name = "gdbserver attach"
request = "attach"
completion = [ { name = "lldb connect url", default = "connect://localhost:3333" }, { name = "file", completion = "filename" }, "pid" ]
args = { console = "internalConsole", attachCommands = [ "platform select remote-gdb-server", "platform connect {0}", "file {1}", "attach {2}" ] }

[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true

[[language]]
name = "typst"
auto-format = true
formatter.command = "typstyle"
language-servers = ["tinymist"]

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "lua"
auto-format = true

[[language]]
name = "json"
auto-format = true

[[language]]
name = "css"
auto-format = true

[[language]]
name = "html"
auto-format = true

[[language]]
name = "c-sharp"
auto-format = true

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "jsx"
auto-format = true

[[language]]
name = "tsx"
auto-format = true

[[language]]
name = "typespec"
auto-format = true
