#!/bin/bash

alias vim="~/bin/vim"
alias nvim="~/bin/vim"

alias que_hacer="vim ~/.local/que_hacer/index.md"

alias mineria="cd ~/apuntes/universidad/mineria/"
alias simula="cd ~/apuntes/universidad/simula/"
alias redes_opticas="cd ~/apuntes/universidad/redes_opticas/"
alias fisica="cd ~/apuntes/universidad/fisica/"
alias economia="cd ~/apuntes/universidad/economia/"
alias numerico="cd ~/apuntes/universidad/numerico/"
alias horario="eog ~/Imágenes/Horario_2021-1.png"

alias data_science="cd ~/code/universidad/data_science"

alias diff="diff -s"
alias beagle="cd ~/Documentos/proyectos/proyecto_gonzalo"
alias less"less -r"
alias mpv="mpv --no-audio-display"

if [ "$TERM" = "xterm-kitty" ]
then
      #alias image="kitty +kitten icat"
      alias diff="kitty +kitten diff"
      alias gitkittydiff="git difftool --no-symlinks --dir-diff"
fi


# Tcl
#alias tclsh="rlwrap tclsh"

# DOCKER
# alias mongodb="sudo docker run --rm -d -p 27017-27019:27017-27019 --name mongodb mongo:4.4"


## PYNQ
alias pynq="sudo chmod 777 /dev/ttyUSB1;    cu -l /dev/ttyUSB1 -f -s 115200 --parity=none"

# Directorios importantes
alias libros="cd ~/Documentos/libros"
alias zero="cd ~/apuntes/usm_zero"
alias apuntes="cd ~/apuntes"
alias apuntes_py="cd ~/apuntes/programming/python"

# Usm Zero
alias connectcore="cu -l /dev/ttyUSB0 -s 115200"
alias qt="cd ~/apuntes/qt"

# Configuraciones
alias czsh="vim ~/.zshrc"
alias cnvim="vim ~/.config/nvim/init.vim"
alias czathura="vim ~/.config/zathura/zathurarc"
alias ctmux="vim ~/.tmux.conf"
alias ckitty="vim ~/.config/kitty/kitty.conf"

# Enlaces rápidos
alias descargas="cd ~/Descargas/"
alias musica="cd ~/musica"
alias videos="cd ~/Vídeos"
alias images="cd ~/Imágenes"

# Ocio
alias youtube_audio="youtube-dl --config-location ~/.config/youtube-dl/config_audio"
alias youtube_video="youtube-dl --config-location ~/.config/youtube-dl/config_video"
alias youtube_update="pip3 install youtube-dl --upgrade"

# Basicos
alias aliases="vim ~/.config/aliasrc"
alias a..="source ~/.zshrc"
alias ls="ls --sort=extension --color=auto --indicator-style=file-type --group-directories-first"
alias l="clear ; ls -A"
alias L="ls -lAh --color=auto"
alias tree="tree -a -I .git"
alias CU="sudo chmod 777 /dev/ttyUSB0; cu -l /dev/ttyUSB0"
alias nautilus="nautilus . &> /dev/null &"

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

#ESP32
# alias esp32_init="export IDF_PATH='$HOME/source/ESP-IDF/esp-idf'; . ~/source/ESP-IDF/esp-idf/export.sh"

# Windows
alias WINDOWS="sudo mount /dev/sda3 /mnt/kali"
alias UNWINDOWS="sudo umount /mnt/kali"

## APLICACIONES
alias gdb="gdb -q"
alias BOOKS="vim ~/bin/.books"
