[server]
browser = "default"
follow_symlink = false

[ai]
rules = ""
mode = "manual"

[language_servers.basedpyright]

[language_servers.ty]

[language_servers.pylsp]
enable_pydocstyle = false
enable_pylint = false
enabled = true
enable_mypy = true
enable_flake8 = false
enable_pyflakes = false
enable_ruff = true

[experimental]

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[runtime]
default_sql_output = "auto"
output_max_bytes = 8000000
auto_instantiate = true
std_stream_max_bytes = 1000000
watcher_on_save = "lazy"
auto_reload = "off"
on_cell_change = "autorun"
reactive_tests = true
default_auto_download = []

[display]
cell_output = "above"
reference_highlighting = false
default_table_max_columns = 50
dataframes = "rich"
code_editor_font_size = 14
default_table_page_size = 10
theme = "light"
default_width = "medium"

[completion]
activate_on_typing = true
copilot = false

[diagnostics]

[formatting]
line_length = 100

[package_management]
manager = "uv"

[snippets]
include_default_snippets = true
custom_paths = []

[save]
autosave_delay = 1000
format_on_save = true
autosave = "after_delay"
